-- ===================================================================
-- Retire the deprecated sheets model.
--
-- 0007 added sheet_connections beside sheet_mappings and copied the live row
-- across, but no application code was ever pointed at the new table — the
-- runtime kept writing to the deprecated one. This finishes the move: data is
-- carried over first, then the old columns and table are dropped, so there is
-- exactly one model afterwards instead of two.
--
-- Everything above the DDL block preserves rows the app already has. It must
-- run first: several of the DDL statements below add NOT NULL constraints that
-- would fail against rows the old code wrote.
-- ===================================================================

-- Any mapping created through the app since 0007 has no connection row yet.
-- Same id on purpose, so sync_jobs.mapping_id keeps pointing at the right thing.
INSERT INTO "sheet_connections"
  (id, project_id, audience, spreadsheet_id, tab_name, mode, mapping,
   header_row, client_editable, template_version, status, last_sync_at, created_at)
SELECT m.id, m.project_id, 'client', m.spreadsheet_id, m.sheet_name,
       m.mode, m.column_map, m.header_row, false, 1,
       CASE WHEN m.is_enabled THEN 'active' ELSE 'paused' END::"sheet_connection_status",
       m.last_synced_at, m.created_at
FROM "sheet_mappings" m
WHERE NOT EXISTS (
  SELECT 1 FROM "sheet_connections" c WHERE c.id = m.id
);--> statement-breakpoint

-- Jobs queued by the old code carry mapping_id and no connection_id.
UPDATE "sync_jobs" SET connection_id = mapping_id
 WHERE connection_id IS NULL AND mapping_id IS NOT NULL;--> statement-breakpoint

-- The idempotency key is about to become NOT NULL. A job's own id is unique
-- and stable, so it is a safe key for anything queued before keys existed.
UPDATE "sync_jobs" SET idempotency_key = 'legacy:' || id::text
 WHERE idempotency_key IS NULL;--> statement-breakpoint

-- A job with no resolvable connection can never be written anywhere. It is
-- dropped rather than blocking the constraint; the work log it came from is
-- untouched and can be re-queued from the Sync tab.
DELETE FROM "sync_jobs" WHERE connection_id IS NULL;--> statement-breakpoint
DELETE FROM "sheet_row_links" WHERE connection_id IS NULL;--> statement-breakpoint

-- THE PRIVACY FIX, as a data migration.
--
-- Work logs written since 0007 have their text in the deprecated `notes`
-- column and NULL in `internal_notes`, because the code was never moved over.
-- `notes` was being written into client spreadsheets, so every existing value
-- is treated as internal-only: it moves to internal_notes and NOTHING is
-- promoted to client_update. A client-visible note is now something a person
-- has to write on purpose.
UPDATE "work_logs" SET internal_notes = notes
 WHERE internal_notes IS NULL;--> statement-breakpoint
UPDATE "work_logs" SET internal_notes = ''
 WHERE internal_notes IS NULL;--> statement-breakpoint

-- Same for the revision chain, which mirrors the work log columns.
UPDATE "worklog_revisions" SET internal_notes = ''
 WHERE internal_notes IS NULL;--> statement-breakpoint

-- ===================================================================
-- DDL. Generated by drizzle-kit; the data migration above is hand-written.
-- ===================================================================
ALTER TABLE "sheet_mappings" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
DROP TABLE "sheet_mappings" CASCADE;--> statement-breakpoint
ALTER TABLE "sheet_row_links" ALTER COLUMN "connection_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "sync_jobs" ALTER COLUMN "connection_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "sync_jobs" ALTER COLUMN "idempotency_key" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "work_logs" ALTER COLUMN "internal_notes" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "sheet_row_links" DROP COLUMN "mapping_id";--> statement-breakpoint
ALTER TABLE "sync_jobs" DROP COLUMN "mapping_id";--> statement-breakpoint
ALTER TABLE "sync_jobs" DROP COLUMN "next_attempt_at";--> statement-breakpoint
ALTER TABLE "sync_jobs" DROP COLUMN "completed_at";--> statement-breakpoint
ALTER TABLE "work_logs" DROP COLUMN "notes";
