import { chromium } from "@playwright/test";
const b=await chromium.launch(); const c=await b.newContext({viewport:{width:1440,height:900}});
const p=await c.newPage();
await p.goto("http://localhost:3000/login",{waitUntil:"networkidle"});
await p.fill('input[name="email"]',"ayan@tavren.io"); await p.fill('input[name="password"]',"tavren123");
await Promise.all([p.waitForURL(u=>!u.pathname.startsWith("/login")).catch(()=>{}),p.click('button[type="submit"]')]);
await p.goto("http://localhost:3000/projects",{waitUntil:"networkidle"});
await p.locator('a[href^="/projects/"]').first().click();
await p.waitForURL("**/projects/**"); await p.waitForTimeout(900);
const rail = await p.locator('a[href^="/log?project="]').first();
console.log("1. project rail offers a link, not a form:", await rail.count()>0, "-", (await rail.textContent().catch(()=>""))?.trim());
console.log("   no second log form on the page:       ", (await p.locator('form textarea[name="internalNotes"]').count())===0);
await rail.click();
await p.waitForURL("**/log**"); await p.waitForTimeout(900);
console.log("2. lands on:", new URL(p.url()).pathname + new URL(p.url()).search);
const body = (await p.locator("main").textContent()) ?? "";
console.log("   says it is narrowed:  ", body.includes("Showing"));
console.log("   offers the way out:   ", (await p.locator('a[href="/log"]').count())>0);
const rows = await p.locator("main button").filter({hasText:/General work|—/}).allTextContents();
console.log("   rows shown:", rows.length);
await p.click('a[href="/log"]'); await p.waitForTimeout(900);
const all = await p.locator("main button").filter({hasText:/General work|—/}).allTextContents();
console.log("3. after clearing the filter, rows:", all.length);
await b.close();
